# Generated by Django 5.1.7 on 2025-04-17 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0006_remove_profile_user_remove_project_users_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='image',
            field=models.ImageField(null=True, upload_to='profiles/'),
        ),
    ]
