# Generated by Django 5.1.7 on 2025-04-17 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0007_customuser_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='preferences',
            field=models.JSONField(default=dict),
        ),
    ]
