# Generated by Django 5.1.7 on 2025-03-12 08:00

from django.db import migrations


def insert_data(apps, schema_editor):
    ShortURL = apps.get_model("shortener", "ShortURL")
    objects = [
        ShortURL(
            original_url="https://chat.com/",
            code="ChatGpt",
        ),
        ShortURL(
            original_url="https://stackoverflow.com/",
            code="StackOF",
        ),
        ShortURL(
            original_url="https://github.com/",
            code="GitHub",
        ),
    ]
    ShortURL.objects.bulk_create(
        objs=objects, ignore_conflicts=True,
    )



class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(
            insert_data,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
