# Generated by Django 5.1.7 on 2025-03-13 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0002_insert_data'),
    ]

    operations = [
        migrations.RunSQL(
            sql="UPDATE short_url SET access_count = access_count + 10;",
            reverse_sql="UPDATE short_url SET access_count = access_count - 10;",
        ),
    ]
