# Generated by Django 5.1.3 on 2024-11-25 12:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_orm', '0004_project'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="ALTER TABLE django_orm_project_users RENAME TO django_orm_project_user",
                    reverse_sql="ALTER TABLE django_orm_project_user RENAME TO django_orm_project_users",
                )
            ],
            state_operations=[
                migrations.CreateModel(
                    name='ProjectUser',
                    fields=[
                        ('id',
                         models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        # ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('project',
                         models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_orm.project')),
                        ('user',
                         models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                    ],
                    options={
                        'db_table': 'django_orm_project_user',
                    },
                ),
                migrations.AlterField(
                    model_name='project',
                    name='users',
                    field=models.ManyToManyField(through='django_orm.ProjectUser', to=settings.AUTH_USER_MODEL),
                ),
            ],
        ),
        migrations.AddField(
            model_name="projectuser",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        )
    ]
