# Generated by Django 5.1.3 on 2024-11-25 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_orm', '0007_user_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='social_provider',
            field=models.CharField(choices=[('kakao', 'Kakao'), ('naver', 'Naver'), ('google', 'Google')], max_length=8, null=True),
        ),
    ]
