# Generated by Django 5.1.3 on 2024-11-25 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_orm', '0008_user_social_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(null=True, upload_to='profiles/'),
        ),
    ]
