# Generated by Django 5.1.3 on 2024-11-26 07:12

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_orm', '0012_profile_created_at_profile_updated_at'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='profile',
            managers=[
                ('with_images', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='profile_image',
            new_name='image',
        ),
    ]
